language: node_js
node_js:
- 9.10.1

before_script:
- npm install

script:
- "./node_modules/.bin/ng build --prod --aot"

deploy:
  on:
    branch: master
  provider: firebase
  skip-cleanup: true
  token:
    secure: kxl8vlwGg0yZsBtAiF2sOcfbRfBNT9InGtAccACShh5cMeSVHQxuKR6e7qD0A9oOiz6Vqu5CvB0zCOY3JXJKzHuPuAZ8Vb5H+gOHHuQgAwz2y6QISqYOd+NGq2QxUqN4jw5DOHYmTHmPWc58D0/sQD/utXWLPLdHvqWU+L0JzaJ5GRaetibJnt7DQ8vYFMR8938LsWeODXeQoXXUM+o4GCUwbw9M/6o1FAK8fQiOWSGGMiZL9givYs4qQvLS14ofNF9FvkU2q3ndVWXpaE5cIrp7ddwi1KPIDi6t+o0UWq/z3NN5jnr4ec5BhjZHE8d1xK5T9CsdxHMDEo4j8QbMS5n8XmHzHPhd/PfWf8UJBYT5GucuHcmCFrXvlFcGXXplRBvGguz5RwobHcoWieZ6tDXMVNC4vWypM7QfHlfmO30/Tt/pvFW8gCNjaGSDDO9m+3DO4GvDDqNFwXQ2ykHt9XIGKLF6ayBb+k3wVXk2pFvXg5v0r0QqC/nwjTw7zF501i0KBMed4WXGti0vWcZTWoS7oPGQ9Vny8kuT4jPKeiCnCel8CjJXCypuOOKZ4cs3v9VcMxvDuvpKsGA6SeKBnEVikQPNhPxdKkwOX6fpS33n4rsrsAxP0wYNaOvDmnt3SVruEJr6gWc6A/4ssRLxfECYUonywYGJFmI/UFbG5Qc=
  project: "portfolio-4b785"
