language: node_js
node_js:
- '9.10.1'

before_script:
- npm install

script:
- "./node_modules/.bin/ng build --prod --aot"

deploy:
  on:
    branch: master
  provider: firebase
  skip-cleanup: true
  project: "portfolio-4f023"
