language: node_js
node_js:
- 9.10.1
before_script:
- npm install
script:
- "./node_modules/.bin/ng build --prod --aot"
deploy:
  on:
    branch: master
  provider: firebase
  skip-cleanup: true
  token:
    secure: Uy7CE+kfxJQJb8GZxpvJmxeSygD8HpPnOhfpQqthFWi8TpP+v41TA6AmQ6CX0EYUZhk3JU6FzLdyzhLpxUflh9glHo8ygQPPb/ht5pLprrSDGJAllY0pmP4Z6LFSSeg0mKW1dLkKpIsXf5NRNvSjTSIVshl5+uFEWWEV3Xp/+Rg0YdooW/YSPXe9L3Eem65lgwnn8NIS7U8QYndac8IOz7i3hoS3Hjka2sSHRKj0m6717ESbsci9CypQZRU0xKQND7MtY1mglHmVCc4tdPfTKiDgWXhCkEbyHBFz/jJs45o+DAUHDvi5/ge9FgAIii2FaviwMjQT384E2wuGdaqdaYVJFDTH3F2cVtk0TvlhkBxJieix19t3VNXiyG3eUBWVlYUDeaU9yQPOWcoAW99mWC+mzp1TJBWUtWSg5URaTR6Xu+yFjqWwMylOKgvV29eRg6Y0L6v3Q/yxV7IYimdyQlkieBL/3MBEW9B1aFjsk5jFAgmVapzs7il7zbHviYRwgkdVGkXN6OkFwTm2706q26I4cCwlJ0SkEv/eLpc8dx0HUb5+L6P2In9MuB3pHKd04R17E15+BggpAxnd0DA0wn3bGXVopU5sG2qahR+V/2CStLcgKe0ks5OfJ1chsbTSCCEWEcrgCPZ70ZebGzZLSk0SN7e3NzE9dBi25IxX3B0=
  project: portfolio-644fa
